In [3]:
#3. Find the shape, size and dimension of the following array?
#arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#Importing python library numpy
import numpy as np

#Creating an array
a =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#Finding the shape, size and dimension of the array
print("Shape of array is:",a.shape)
print("Size of array is:",a.size)
print("dimension of array is:",a.ndim)


Shape of array is: (3, 4)
Size of array is: 12
dimension of array is: 2


In [ ]:
#1. What is a Python library? Why do we use Python libraries?

Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. 
It contains bundles of code that can be used repeatedly in different programs. 
It makes Python Programming simpler and convenient for the programmer. 
As we don’t need to write the same code again and again for different programs.
When we link a library with our program and run that program,the linker automatically searches for that library. 
It extracts the functionalities of that library and interprets the program accordingly.

In [ ]:
#2. What is the difference between Numpy array and  List?

Python Lists -->

Element Overhead: Lists in Python store additional information about each element, such as its type and reference count. 
                   This overhead can be significant when dealing with a large number of elements.
Datatype        : Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.
Memory Fragmentation: Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.
Performance      : Lists are not optimized for numerical computations and may have slower mathematical operations due 
                    to Python’s interpretation overhead. They are generally used as general-purpose data structures.
Functionality    : Lists can store any data type, but lack specialized NumPy functions for numerical operations.


Numpy Arrays -->

Homogeneous Data  : NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.4
Fixed Data Type   : NumPy arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information 
                    for each element.
Contiguous Memory : NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.
Array Metadata    : NumPy arrays have extra metadata like shape, strides, and data type. However, this overhead is usually smaller than the per-element overhead in lists.
Performance       : NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. 
                    These operations are implemented in C, resulting in faster performance than equivalent operations on lists.


In [6]:
#4. Write python code to access the first row of the following array? 
#[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#Importing the package from numpy library
import numpy as np

#creating an numpy array
arr =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#Printing the first row of array
print("First row in the array is:",arr[0])


First row in the array is: [1 2 3 4]


In [5]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
#[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#Importing the package from numpy library
import numpy as np

#creating an numpy array
arr =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#Printing the element
print("Element at the third row and fourth column is:",arr[2,3])

Element at the third row and fourth column is: 12


In [2]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#Importing the package from numpy library
import numpy as np

#creating an numpy array
arr =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("Original array isarr)

arr[0:3,[1,3]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [3]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

#importing package from python library
import numpy as np

#creating an array of 3*3 matrix with values between 0 and 1
arr = np.random.rand(3,3)

print("Array with values between 0 and 1 is:",arr)

Array with values between 0 and 1 is: [[0.33131068 0.95942362 0.02700816]
 [0.64771248 0.70100515 0.97483287]
 [0.98690599 0.03039838 0.09244953]]


In [ ]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

The difference between rand and randn is that rand returns random numbers sampled from a uniform distribution over the interval [0,1), 
while randn instead samples from a normal (a.k.a. Gaussian) distribution with a mean of 0 and a variance of 1.

In [6]:
#9. Write code to increase the dimension of the following array? [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#importing package from python library
import numpy as np

#creating an numpy array
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#increasing the dimension of the array using expand_dims function
arr1 = np.expand_dims(arr , axis  = 0)
print("Array with new dimesion is:",arr1)

Array with new dimesion is: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [11]:
#10. How to transpose the following array in NumPy?[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

#importing package from python library
import numpy as np

#creating an numpy array
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

Transpose_arr = arr.T
print("Transposed array is:",Transpose_arr)

Transposed array is: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [22]:
#11. Consider the following matrix and perform operations(multiply index wise and matrix ,addition,substraction,add,divide)
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

#importing package from python library
import numpy as np

##creating an numpy array
matrix1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrix2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

#1.Index wise multiplication
mul_index_matrix = matrix1 * matrix2
print("Index wise multiplied matrix is:", mul_index_matrix)

#2.Matrix Multiplication
#matix_mul = np.dot(matrix1,matrix2)
#print("Matrix multied matrix is:",matrix_mul)
#3.Add both the matics
add_matrix = matrix1 + matrix2
print("matrix after added is:",add_matrix)

#4.Subtact matix B from matrix A
sub_matrix = matrix1 - matrix2
print("Matrix after subtracting is :",sub_matrix)

#5.Diide Matix B by A

div_matrix = matrix2 / matrix1
print("Matrix values after division is:",div_matrix)

Index wise multiplied matrix is: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
matrix after added is: [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix after subtracting is : [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix values after division is: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#12. Which function in Numpy can be used to swap the byte order of an array?

The ndarray.byteswap() method swaps the bytes of the array elements. 
It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.
byteswap() method does not work on arrays of strings.


In [ ]:
#13. What is the significance of the np.linalg.inv function?

numpy.linalg.inv() function to calculate the inverse of a matrix. 
The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [ ]:
#14. What does the np.reshape function do, and how is it used?

The numpy.reshape() function shapes an array without changing the data of the array.

Syntax: numpy.reshape(array, shape, order = 'C')
Parameters : 

array : [array_like]Input array
shape : [int or tuples of int] e.g. if we are arranging an array with 10 elements then shaping
        it like numpy.reshape(4, 8) is wrong; we can do numpy.reshape(2, 5) or (5, 2)
order  : [C-contiguous, F-contiguous, A-contiguous; optional]         
         C-contiguous order in memory(last index varies the fastest)
         C order means that operating row-rise on the array will be 

In [2]:
#how reshape is used?

#importing package from python library
import numpy as np

##creating an numpy array
arr1 = np.array([[2,3,4],[7,8,9]])

#using reshape function to convert from (2,3) to (3,2)
np.reshape(arr1 , (3,2))



array([[2, 3],
       [4, 7],
       [8, 9]])

In [ ]:
#15. What is broadcasting in Numpy?

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.Subject to certain constraints, 
the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. 

It does this without making needless copies of data and usually leads to efficient algorithm implementations.